# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.1.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *

import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(960, 640)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(960, 640))
        MainWindow.setMaximumSize(QSize(960, 640))
        icon = QIcon()
        icon.addFile(u":/icons/icons/node-magnifier.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.actionImport_files = QAction(MainWindow)
        self.actionImport_files.setObjectName(u"actionImport_files")
        icon1 = QIcon()
        icon1.addFile(u":/icons/icons/document-import.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionImport_files.setIcon(icon1)
        self.actionExport_files = QAction(MainWindow)
        self.actionExport_files.setObjectName(u"actionExport_files")
        icon2 = QIcon()
        icon2.addFile(u":/icons/icons/document-export.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionExport_files.setIcon(icon2)
        self.actionStart_analysis_tp = QAction(MainWindow)
        self.actionStart_analysis_tp.setObjectName(u"actionStart_analysis_tp")
        icon3 = QIcon()
        icon3.addFile(u":/icons/icons/control.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionStart_analysis_tp.setIcon(icon3)
        self.actionRemove_selected = QAction(MainWindow)
        self.actionRemove_selected.setObjectName(u"actionRemove_selected")
        icon4 = QIcon()
        icon4.addFile(u":/icons/icons/minus.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionRemove_selected.setIcon(icon4)
        self.actionClear_summary = QAction(MainWindow)
        self.actionClear_summary.setObjectName(u"actionClear_summary")
        icon5 = QIcon()
        icon5.addFile(u":/icons/icons/broom.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionClear_summary.setIcon(icon5)
        self.actionDiffusivity_ranges = QAction(MainWindow)
        self.actionDiffusivity_ranges.setObjectName(u"actionDiffusivity_ranges")
        icon6 = QIcon()
        icon6.addFile(u":/icons/icons/ui-slider-050.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionDiffusivity_ranges.setIcon(icon6)
        self.actionApplication_configuration = QAction(MainWindow)
        self.actionApplication_configuration.setObjectName(u"actionApplication_configuration")
        icon7 = QIcon()
        icon7.addFile(u":/icons/icons/application-task.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionApplication_configuration.setIcon(icon7)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        icon8 = QIcon()
        icon8.addFile(u":/icons/icons/information.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAbout.setIcon(icon8)
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionExit.setMenuRole(QAction.QuitRole)
        self.actionStart_analysis = QAction(MainWindow)
        self.actionStart_analysis.setObjectName(u"actionStart_analysis")
        self.actionStart_analysis.setIcon(icon3)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.summary_view = QTableWidget(self.centralwidget)
        if (self.summary_view.columnCount() < 4):
            self.summary_view.setColumnCount(4)
        __qtablewidgetitem = QTableWidgetItem()
        self.summary_view.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.summary_view.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        __qtablewidgetitem2.setTextAlignment(Qt.AlignCenter);
        self.summary_view.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        __qtablewidgetitem3.setTextAlignment(Qt.AlignCenter);
        self.summary_view.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        self.summary_view.setObjectName(u"summary_view")
        self.summary_view.setFrameShape(QFrame.Panel)
        self.summary_view.setFrameShadow(QFrame.Sunken)
        self.summary_view.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.summary_view.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.summary_view.setAutoScroll(False)
        self.summary_view.setProperty("showDropIndicator", False)
        self.summary_view.setAlternatingRowColors(False)
        self.summary_view.horizontalHeader().setMinimumSectionSize(43)
        self.summary_view.horizontalHeader().setDefaultSectionSize(100)
        self.summary_view.verticalHeader().setVisible(False)

        self.verticalLayout.addWidget(self.summary_view)

        self.summary_total = QTreeWidget(self.centralwidget)
        self.summary_total.setObjectName(u"summary_total")
        self.summary_total.setMaximumSize(QSize(16777215, 24))
        self.summary_total.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.summary_total.setFrameShape(QFrame.NoFrame)
        self.summary_total.setFrameShadow(QFrame.Plain)
        self.summary_total.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.summary_total.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.summary_total.setAutoScroll(False)
        self.summary_total.setProperty("showDropIndicator", False)
        self.summary_total.setItemsExpandable(False)
        self.summary_total.header().setVisible(False)
        self.summary_total.header().setMinimumSectionSize(43)
        self.summary_total.header().setDefaultSectionSize(100)
        self.summary_total.header().setStretchLastSection(False)

        self.verticalLayout.addWidget(self.summary_total)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 960, 22))
        self.menu_File = QMenu(self.menuBar)
        self.menu_File.setObjectName(u"menu_File")
        self.menuEdit = QMenu(self.menuBar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuConfigurations = QMenu(self.menuEdit)
        self.menuConfigurations.setObjectName(u"menuConfigurations")
        self.menuHelp = QMenu(self.menuBar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menu_File.addAction(self.actionImport_files)
        self.menu_File.addAction(self.actionExport_files)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionStart_analysis_tp)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.menuConfigurations.menuAction())
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionRemove_selected)
        self.menuEdit.addAction(self.actionClear_summary)
        self.menuConfigurations.addAction(self.actionDiffusivity_ranges)
        self.menuConfigurations.addAction(self.actionApplication_configuration)
        self.menuHelp.addAction(self.actionAbout)
        self.toolBar.addAction(self.actionImport_files)
        self.toolBar.addAction(self.actionExport_files)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRemove_selected)
        self.toolBar.addAction(self.actionClear_summary)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionStart_analysis_tp)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionDiffusivity_ranges)
        self.toolBar.addAction(self.actionApplication_configuration)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Multiple Particle Tracking", None))
        self.actionImport_files.setText(QCoreApplication.translate("MainWindow", u"&Import files...", None))
#if QT_CONFIG(shortcut)
        self.actionImport_files.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+I", None))
#endif // QT_CONFIG(shortcut)
        self.actionExport_files.setText(QCoreApplication.translate("MainWindow", u"&Export files...", None))
#if QT_CONFIG(shortcut)
        self.actionExport_files.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+E", None))
#endif // QT_CONFIG(shortcut)
        self.actionStart_analysis_tp.setText(QCoreApplication.translate("MainWindow", u"&Start analysis", None))
#if QT_CONFIG(shortcut)
        self.actionStart_analysis_tp.setShortcut(QCoreApplication.translate("MainWindow", u"F5", None))
#endif // QT_CONFIG(shortcut)
        self.actionRemove_selected.setText(QCoreApplication.translate("MainWindow", u"&Remove selected", None))
        self.actionClear_summary.setText(QCoreApplication.translate("MainWindow", u"&Clear summary", None))
        self.actionDiffusivity_ranges.setText(QCoreApplication.translate("MainWindow", u"Diffusivity ranges", None))
        self.actionApplication_configuration.setText(QCoreApplication.translate("MainWindow", u"Application configuration", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"&About", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionStart_analysis.setText(QCoreApplication.translate("MainWindow", u"Start Analysis (without TrackPy)", None))
        ___qtablewidgetitem = self.summary_view.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"RM", None));
        ___qtablewidgetitem1 = self.summary_view.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"File name", None));
        ___qtablewidgetitem2 = self.summary_view.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Trajectories", None));
        ___qtablewidgetitem3 = self.summary_view.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Valid trajectories", None));
        ___qtreewidgetitem = self.summary_total.headerItem()
        ___qtreewidgetitem.setText(2, QCoreApplication.translate("MainWindow", u"total_valid_trajectories", None));
        ___qtreewidgetitem.setText(1, QCoreApplication.translate("MainWindow", u"total_trajectories", None));
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("MainWindow", u"total", None));
        self.menu_File.setTitle(QCoreApplication.translate("MainWindow", u"&File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"&Tools", None))
        self.menuConfigurations.setTitle(QCoreApplication.translate("MainWindow", u"Configurations", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"&Help", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

